- name: Playbook to add hosts
  hosts: all
  remote_user: ubuntu
  tasks:

  - name: Update hosts
    lineinfile:
      path: /etc/hosts
      state: present
      line: "{{ item }}"
    with_items:
      - '107.154.135.229  	apicm-staging.copaair.com'
      - '107.154.135.229  	apicm-uat.copaair.com'
      - '107.154.135.229  	copacom-staging.copaair.com'
      - '107.154.135.229  	copacom-uat.copaair.com'

  - name: clone git repo
    git:
      repo: https://github.com/fajardodiaz/jmeter_test.git
      dest: /home/ubuntu/jmeter_test
      clone: yes

  - name: Install jmeter dependencies
    shell:
      cmd: cd /opt/apache-jmeter-5.5/bin && ./PluginsManagerCMD.sh install-for-jmx /home/ubuntu/jmeter_test/CopaCom.jmx